### ISSUE TITLE
bkgsmooth html error 404

### ISSUE THREAD

**Issue by jmao2014** [spex-xray/pyspextools#4]
Hi Jelle, 

It seems that the documentation of bkgsmooth is not valid. 

https://spex-xray.github.io/pyspextools/tutorials/bkgsmooth.html

**Comment by jdeplaa** [comment]
Hi Junjie,

Well spotted. I just noticed that I uploaded the wrong documentation version this afternoon. This has now been corrected. The bkgsmooth tool is not yet part of this release.

Jelle.
